# Generated by Django 3.2.5 on 2021-07-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210704_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Hospital',
        ),
    ]
