# Generated by Django 3.2.5 on 2021-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210704_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='csv_file',
            field=models.FileField(default=' ', upload_to='documents'),
        ),
    ]
